apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard # ! what is this
  accessModes:
    - ReadWriteOnce # mean: con only rw by single node
    # - ReadOnlyMany
    # - ReadWriteMany
    # These two opts do not work with hostPath because hostPath do not allow multiple node claim a volume
  hostPath:
    path: /data
    type: DirectoryOrCreate
